CREATE TABLE commercial.alc_transaction_wholesaler
(
    WHOLESALER_CODE String,
    WHOLESALER_NAME String,
    WHOLESALER_CENTRE_CODE String,
    WHOLESALER_CENTRE_NAME String,
    CUSTOMER_BRANCH_CODE String,
    CUSTOMER_BRANCH_NAME String,
    CUSTOMER_BRANCH_ADDRESS String,
    CUSTOMER_BRANCH_PHONE String,
    DELIVERY_DATE Date,
    JAN_CODE String,
    PRODUCT_NAME String,
    CAN_QUANTITY Nullable(Decimal(16,8))
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(DELIVERY_DATE)
ORDER BY (DELIVERY_DATE, WHOLESALER_CODE, WHOLESALER_CENTRE_CODE, CUSTOMER_BRANCH_CODE, JAN_CODE);